### ISSUE TITLE
option to remove theme file

### ISSUE THREAD

**Issue by ctf0** [miqh/vscode-core-theme#3]
is that possible ? atm its only doable vie manual file deletion.

**Comment by miqh** [comment]
Apologies about the delayed response @ctf0.

If you're referring to the JSON files underneath the `themes` directory inside the folder for this extension, they shouldn't be removed. I believe VS Code needs to read from these files in order to apply the designated theme colours every time the editor is opened.

On the other hand, files in the `templates` directory _could_ be removed after the `Generate Themes` command is run (i.e. produces the files under the `themes` directory), but I'd discourage this as well. The reason is if any new theme variables are covered, the themes need to be regenerated. If the theme you're using no longer has a corresponding template, you'll end up with a bad theme configuration state.

Is there something that prompted you to ask about an option to remove these files?

**Comment by ctf0** [comment]
no thats it, thanx for the headsup
